using System;
using System.Collections.Generic;
using System.Linq;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using AIOverhaulPatcher.Utilities;
using AIOverhaulPatcher.Settings;
using AIOverhaulPatcher.Patching;
using Noggog;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Mutagen.Bethesda.Plugins; 

namespace AIOverhaulPatcher
{
    public class Program
    {
        private static Lazy<Settings.Settings> _settings = null!;
        const string AioPatchName = "AIOPatch.esp";
        public static Task<int> Main(string[] args)
        {
            if (args.Length > 0 && string.Equals(args[0], "verify-quest-alpc", StringComparison.OrdinalIgnoreCase))
                return Task.FromResult(Verify.QuestAlpcMergeVerifier.Run());

            // Diagnostic: log raw args received so we can see how Synthesis forwards them.
            Console.WriteLine($"Raw args length: {args.Length}");
            for (int _i = 0; _i < args.Length; _i++)
                Console.WriteLine($"arg[{_i}]: '{args[_i]}'");

            // If Synthesis (or other caller) passes the entire app argument string as a single
            // quoted argument, split it into proper args here so the pipeline receives them.
            if (args.Length == 1)
            {
                var single = args[0];
                if (single.Contains("--DataFolderPath") || single.Contains("run-patcher") || single.Contains("--PatcherName"))
                {
                    args = SplitArgs(single);
                }
            }

            // If we still don't have useful args (Synthesis may invoke `dotnet run` so the
            // host command-line contains the app args but they don't appear in `args`),
            // try to extract them from Environment.CommandLine.
            if (args.Length == 0 || (args.Length == 1 && !args[0].Contains("--DataFolderPath") && !args[0].Contains("run-patcher")))
            {
                try
                {
                    var cmdLine = Environment.CommandLine ?? string.Empty;
                    // Look for the token 'run-patcher' and take everything after it as app args
                    var m = Regex.Match(cmdLine, "(?:\\s|\\\")run-patcher(?:\\s+)(.*)$", RegexOptions.Singleline);
                    if (m.Success)
                    {
                        var tail = m.Groups[1].Value.Trim();
                        if (!string.IsNullOrEmpty(tail))
                        {
                            Console.WriteLine("Parsed args from Environment.CommandLine.");
                            args = SplitArgs(tail);
                        }
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine("Failed to parse Environment.CommandLine: " + ex.Message);
                }
            }

            return SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch, new PatcherPreferences()
                {
                    ExclusionMods = new List<ModKey>()
                    {
                         new ModKey(AioPatchName, ModType.Plugin),
                         new ModKey("Nemesis PCEA.esp", ModType.Plugin)
                    }
                } )
                .SetAutogeneratedSettings("settings", "settings.json", out _settings)
                .SetTypicalOpen(GameRelease.SkyrimSE, AioPatchName)
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {

            var AIOverhaul = state.LoadOrder.GetModByFileName("AI Overhaul.esp");
            var USLEEP = state.LoadOrder.GetModByFileName("Unofficial Skyrim Special Edition Patch.esp");
            if (USLEEP != null) System.Console.WriteLine("Unofficial Skyrim Special Edition Patch.esp");
            var UsleepOrder = state.LoadOrder.GetFileOrder("Unofficial Skyrim Special Edition Patch.esp");
            System.Console.WriteLine("at " + UsleepOrder);


            if (AIOverhaul == null)
            {
                System.Console.WriteLine("AIOverhaul.esp not found");
                return;
            }

            var aioMods = AioPluginUtilities.GetLoadedAioMods(state);
            var aioModKeys = AioPluginUtilities.GetAioModKeys(aioMods);
            var aioFormKeys = AioPluginUtilities.GetAllAioNpcFormKeys(aioMods);

            int bmax = 10;
            int b = 0;
            int processed = 0;
            int total = aioFormKeys.Count;
            var updatedNpcs = new System.Collections.Generic.List<string>();
            int updatedCount = 0;

            var winningOverrides = state.LoadOrder.PriorityOrder.WinningOverrides<INpcGetter>().Where(x => aioFormKeys.Contains(x.FormKey)).ToList();
            var masterfilenames = AIOverhaul.MasterReferences.Select(x => x.Master.FileName).ToList();
            var MasterFiles = state.LoadOrder.PriorityOrder.Reverse().Where(x => masterfilenames.Contains(x.ModKey.FileName)).ToList();
            var NPCMasters = MasterFiles.Select(x => x.Mod).NotNull().SelectMany(x => x.Npcs).Where(x => aioFormKeys.Contains(x.FormKey)).ToList();

            var allOverrides = state.LoadOrder.PriorityOrder.Reverse().Skip(UsleepOrder + 1).Select(x => x.Mod).NotNull().SelectMany(x => x.Npcs).Where(x => aioFormKeys.Contains(x.FormKey)).ToList();


            System.Console.WriteLine(processed + "/" + total + " Npcs");
            foreach (var formKey in aioFormKeys)
            {
                var aioNpc = AioPluginUtilities.GetWinningAioNpc(formKey, state, aioModKeys);
                if (aioNpc == null) continue;

                if (_settings.Value.IgnorePlayerRecord &&  new List<uint>() { 7, 14 }.Contains(aioNpc.FormKey.ID)) continue;

                if (b >= bmax)
                {
                    b = 0;
                    System.Console.WriteLine(processed + "/" + total + " Npcs");
                }

                var winningOverride = winningOverrides.Where(x => x.FormKey == aioNpc.FormKey).First();
                var Masters = NPCMasters.Where(x => x.FormKey == aioNpc.FormKey).ToList();
                var winningMaster = Masters.FirstOrDefault();
                if (winningMaster == null) winningMaster = state.LoadOrder.PriorityOrder.Select(x => x.Mod).NotNull().SelectMany(x => x.Npcs).Where(x => x.FormKey == aioNpc.FormKey).First();
                var overrides = allOverrides.Where(x => x.FormKey == aioNpc.FormKey).ToList();

                bool change = false;

                var patchNpc = state.PatchMod.Npcs.GetOrAddAsOverride(winningOverride);
                if (aioNpc.IsProtected() && !(patchNpc.IsProtected() || (patchNpc.IsEssential() && _settings.Value.MaintainHighestProtectionLevel)))
                {
                    patchNpc.Configuration.Flags = patchNpc.Configuration.Flags.SetFlag(NpcConfiguration.Flag.Protected, true);
                    change = true;


                }

                var flagsChangedByAio = aioNpc.Configuration.Flags ^ winningMaster.Configuration.Flags;
                if (flagsChangedByAio != 0)
                {
                    var beforeFlags = patchNpc.Configuration.Flags;
                    AioPluginUtilities.ForwardAioChangedFlagBits(
                        winningMaster.Configuration.Flags,
                        aioNpc.Configuration.Flags,
                        patchNpc.Configuration.Flags,
                        merged => patchNpc.Configuration.Flags = merged);
                    if (patchNpc.Configuration.Flags != beforeFlags)
                        change = true;
                }

                var templateFlagsChangedByAio = aioNpc.Configuration.TemplateFlags ^ winningMaster.Configuration.TemplateFlags;
                if (templateFlagsChangedByAio != 0)
                {
                    var beforeTemplateFlags = patchNpc.Configuration.TemplateFlags;
                    AioPluginUtilities.ForwardAioChangedTemplateFlagBits(
                        winningMaster.Configuration.TemplateFlags,
                        aioNpc.Configuration.TemplateFlags,
                        patchNpc.Configuration.TemplateFlags,
                        merged => patchNpc.Configuration.TemplateFlags = merged);
                    if (patchNpc.Configuration.TemplateFlags != beforeTemplateFlags)
                        change = true;
                }

                foreach (var fac in aioNpc.Factions)
                    if (!patchNpc.Factions.Select(x => new KeyValuePair<FormKey, int>(x.Faction.FormKey, x.Rank)).Contains(new KeyValuePair<FormKey, int>(fac.Faction.FormKey, fac.Rank)))
                    {
                        patchNpc.Factions.Add(fac.DeepCopy());
                        change = true;

                    }

                var aioPackages = AioPluginUtilities.BuildEffectiveAioPackageOrder(formKey, state, aioModKeys);
                var mergedPackages = AioPluginUtilities.BuildMergedPackageList(
                    aioPackages.EffectiveAioOrder,
                    winningOverride, Masters, overrides);
                var packagesReordered = !AioPluginUtilities.PackageListsEqual(patchNpc.Packages, mergedPackages);
                if (packagesReordered)
                {
                    change = true;
                    patchNpc.Packages.Clear();
                    mergedPackages.ForEach(x => patchNpc.Packages.Add(x));
                }

                var OverwrittenOutfits = Masters.Select(x => x.DefaultOutfit).Select(x => x.FormKey).Distinct().ToHashSet<FormKey>();
                var OverwrittenSleepingOutfit = Masters.Select(x => x.SleepingOutfit).Select(x => x.FormKey).Distinct().ToHashSet<FormKey>();

                FormKey? OverwrittingOutfit = overrides.Select(x => x.DefaultOutfit).Select(x => x.FormKey).Where(x => !x.IsNull && !OverwrittenOutfits.Contains(x)).Prepend(aioNpc.DefaultOutfit.FormKey).LastOrDefault();
                FormKey? OverwrittingSleepingOutfit = overrides.Select(x => x.SleepingOutfit).Select(x => x.FormKey).Where(x => !x.IsNull && !OverwrittenSleepingOutfit.Contains(x)).Prepend(aioNpc.SleepingOutfit.FormKey).LastOrDefault();

                if (aioNpc.DefaultOutfit.FormKey != patchNpc.DefaultOutfit.FormKey)
                {
                    if (OverwrittingOutfit.HasValue && !OverwrittingOutfit.Value.IsNull)
                        patchNpc.DefaultOutfit.SetTo(OverwrittingOutfit);
                    else
                        patchNpc.DefaultOutfit.SetToNull();

                    change = true;

                }

                if (aioNpc.SleepingOutfit.FormKey != patchNpc.SleepingOutfit.FormKey)
                {
                    if (OverwrittingSleepingOutfit.HasValue && !OverwrittingSleepingOutfit.Value.IsNull)
                        patchNpc.SleepingOutfit.SetTo(OverwrittingSleepingOutfit);
                    else
                        patchNpc.SleepingOutfit.SetToNull();
                    change = true;


                }
                if (aioNpc.SpectatorOverridePackageList.FormKey != patchNpc.SpectatorOverridePackageList.FormKey)
                {
                    if (!aioNpc.SpectatorOverridePackageList.IsNull)
                        patchNpc.SpectatorOverridePackageList.SetTo(aioNpc.SpectatorOverridePackageList);
                    else
                        patchNpc.SpectatorOverridePackageList.SetToNull();
                    change = true;

                }

                if (aioNpc.CombatOverridePackageList.FormKey != patchNpc.CombatOverridePackageList.FormKey)
                {
                    if (!aioNpc.CombatOverridePackageList.IsNull)
                        patchNpc.CombatOverridePackageList.SetTo(aioNpc.CombatOverridePackageList);
                    else
                        patchNpc.CombatOverridePackageList.SetToNull();
                    change = true;


                }

                if (aioNpc.ObserveDeadBodyOverridePackageList != patchNpc.ObserveDeadBodyOverridePackageList)
                {
                    patchNpc.ObserveDeadBodyOverridePackageList.SetTo(aioNpc.ObserveDeadBodyOverridePackageList);
                    change = true;
                }

                if (aioNpc.Items != null && _settings.Value.MergeItems)
                {
                    if (patchNpc.Items == null )
                    {
                        patchNpc.Items  = new ExtendedList<ContainerEntry>();
                    }
                    foreach (var item in aioNpc.Items)
                    {
                        if (!patchNpc.Items.Contains(item))
                        {
                            patchNpc.Items.Add(item.DeepCopy());
                            change = true;
                        }
                    } 
                } 


                if (AioPluginUtilities.ShouldForwardAioFormLink(winningMaster.CombatStyle, aioNpc.CombatStyle, winningOverride.CombatStyle))
                {
                    patchNpc.CombatStyle.SetTo(aioNpc.CombatStyle);
                    change = true;
                }

                if (AioPluginUtilities.ShouldForwardAioChange(winningMaster.AIData.Aggression, aioNpc.AIData.Aggression, winningOverride.AIData.Aggression))
                {
                    patchNpc.AIData.Aggression = aioNpc.AIData.Aggression;
                    change = true;
                }

                if (AioPluginUtilities.ShouldForwardAioChange(winningMaster.AIData.Confidence, aioNpc.AIData.Confidence, winningOverride.AIData.Confidence))
                {
                    patchNpc.AIData.Confidence = aioNpc.AIData.Confidence;
                    change = true;
                }

                if (AioPluginUtilities.ShouldForwardAioChange(winningMaster.AIData.Assistance, aioNpc.AIData.Assistance, winningOverride.AIData.Assistance))
                {
                    patchNpc.AIData.Assistance = aioNpc.AIData.Assistance;
                    change = true;
                }

                if (AioPluginUtilities.ShouldForwardAioFormLink(winningMaster.Class, aioNpc.Class, winningOverride.Class))
                {
                    patchNpc.Class.SetTo(aioNpc.Class);
                    change = true;
                }

                if (AioPluginUtilities.ShouldForwardAioPlayerSkills(
                    winningMaster.PlayerSkills,
                    aioNpc.PlayerSkills,
                    winningOverride.PlayerSkills))
                {
                    patchNpc.PlayerSkills = aioNpc.PlayerSkills!.DeepCopy();
                    change = true;
                }

                var masterScriptNames = winningMaster.VirtualMachineAdapter?.Scripts
                    .Select(x => x.Name)
                    .ToHashSet(StringComparer.OrdinalIgnoreCase)
                    ?? new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                var aioScriptNames = aioNpc.VirtualMachineAdapter?.Scripts
                    .Select(x => x.Name)
                    .ToHashSet(StringComparer.OrdinalIgnoreCase)
                    ?? new HashSet<string>(StringComparer.OrdinalIgnoreCase);

                foreach (var scriptName in masterScriptNames.Where(n => !aioScriptNames.Contains(n)))
                {
                    if (patchNpc.VirtualMachineAdapter?.Scripts == null) continue;
                    var removed = patchNpc.VirtualMachineAdapter.Scripts
                        .Where(s => string.Equals(s.Name, scriptName, StringComparison.OrdinalIgnoreCase))
                        .ToList();
                    foreach (var script in removed)
                    {
                        patchNpc.VirtualMachineAdapter.Scripts.Remove(script);
                        change = true;
                    }
                }

                if (aioNpc.VirtualMachineAdapter != null)
                {
                    foreach (var script in aioNpc.VirtualMachineAdapter.Scripts.Where(s => !masterScriptNames.Contains(s.Name)))
                    {
                        if (patchNpc.VirtualMachineAdapter == null)
                            patchNpc.VirtualMachineAdapter = new VirtualMachineAdapter();
                        if (patchNpc.VirtualMachineAdapter.Scripts.Any(s => string.Equals(s.Name, script.Name, StringComparison.OrdinalIgnoreCase)))
                            continue;

                        patchNpc.VirtualMachineAdapter.Scripts.Add(script.DeepCopy());
                        change = true;
                    }
                }

                if (AioPluginUtilities.ShouldForwardAioObjectBounds(
                    winningMaster.ObjectBounds,
                    aioNpc.ObjectBounds,
                    winningOverride.ObjectBounds))
                {
                    patchNpc.ObjectBounds = aioNpc.ObjectBounds.DeepCopy();
                    change = true;
                }


                if (_settings.Value.IgnoreIdenticalToLastOverride && !change)
                {
                    state.PatchMod.Npcs.Remove(aioNpc);
                }
                else if (change)
                {
                    updatedCount++;
                    string displayName = aioNpc.FormKey.ToString();
                    try
                    {
                        if (aioNpc.Name != null)
                            displayName = aioNpc.Name.ToString() ?? displayName;
                        else if (winningOverride != null && winningOverride.Name != null)
                            displayName = winningOverride.Name.ToString() ?? displayName;
                    }
                    catch
                    {
                        displayName = aioNpc.FormKey.ToString();
                    }
                    string masterSource = "unknown";
                    try
                    {
                        if (winningMaster != null)
                            masterSource = winningMaster.FormKey.ModKey.FileName;
                    }
                    catch { }
                    var winningAioModName = AioPluginUtilities.GetWinningAioModKey(aioNpc.FormKey, state, aioModKeys)?.FileName ?? "unknown";
                    var entry = $"{displayName} ({aioNpc.FormKey}) - source: {masterSource} [aio-mod: {winningAioModName}]";
                    updatedNpcs.Add(entry);
                    System.Console.WriteLine("Updated: " + entry);
                }
                b++;
                processed++;
            }
            // summary
            System.Console.WriteLine($"Updated {updatedCount} of {total} NPCs.");
            if (updatedCount > 0)
            {
                System.Console.WriteLine("Updated NPCs:");
                foreach (var e in updatedNpcs)
                    System.Console.WriteLine("  " + e);
            }

            if (_settings.Value.QuestAlpcPatch == QuestAlpcPatchMode.Mg01Only)
                QuestAlpcPatcher.PatchMg01(state, aioModKeys, UsleepOrder, _settings.Value, AIOverhaul);
            else if (_settings.Value.QuestAlpcPatch == QuestAlpcPatchMode.All)
                QuestAlpcPatcher.PatchAll(state, aioModKeys, UsleepOrder, _settings.Value, AIOverhaul, aioMods);

            if (state.PatchMod.ModKey.Name == AioPatchName)
            {
                state.PatchMod.ModHeader.Flags = state.PatchMod.ModHeader.Flags | SkyrimModHeader.HeaderFlag.Small;
            }
        }

        private static string[] SplitArgs(string commandLine)
        {
            var matches = Regex.Matches(commandLine, "[\"]([^\"]*)[\"]|'([^']*)'|[^ \t\r\n]+");
            var parts = new List<string>();
            foreach (Match m in matches)
            {
                var v = m.Value;
                if (v.Length >= 2 && ((v[0] == '"' && v[v.Length - 1] == '"') || (v[0] == '\'' && v[v.Length - 1] == '\'')))
                    v = v.Substring(1, v.Length - 2);
                parts.Add(v);
            }
            return parts.ToArray();
        }
    }
}
